
# Enable Spark Reporter
extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport.html
basefolder.name=test-output/SparkReport/SparkReport.html
extent.reporter.spark.theme=dark
basefolder.datetimepattern=d-MMM-YY HH-mm-ss
systeminfo.build=v2.89.56

# System Info
systeminfo.OS=Windows
systeminfo.User=padmapriya
systeminfo.Environment=QA
systeminfo.Browser=Chrome